### ISSUE TITLE
Figure out how to apply watchdog

### ISSUE THREAD

**Issue by caycehouse** [caycehouse/home-ops#1266]
Figure out how to apply the watchdog config with the new config apply setup.

```yaml
---
apiVersion: v1alpha1
kind: WatchdogTimerConfig
device: /dev/watchdog0
timeout: 5m
```
